#ifndef QSURFACEPARETOTSPRESULTSVIEWMODEL_H
#define QSURFACEPARETOTSPRESULTSVIEWMODEL_H


class QSurfaceParetoTspResultsViewModel
{
public:
    QSurfaceParetoTspResultsViewModel();
};

#endif // QSURFACEPARETOTSPRESULTSVIEWMODEL_H