#ifndef TSPDUALSOLVERRESULTSSURFACEPARETOVIEWMODEL_H
#define TSPDUALSOLVERRESULTSSURFACEPARETOVIEWMODEL_H


class TspDualSolverResultsSurfaceParetoViewModel
{
public:
    TspDualSolverResultsSurfaceParetoViewModel();
};

#endif // TSPDUALSOLVERRESULTSSURFACEPARETOVIEWMODEL_H